"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4XHRQLyNMjm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from "next/link";
import { JSX, SVGProps } from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import { Button } from "@/components/ui/button";

export function FeaturesPage() {
	const { data: session, status } = useSession();

	const handleSignOut = async () => {
		signOut();
	};
	const handleSignIn = async () => {
		signIn();
	};

	return (
		<div className="flex flex-col min-h-[100dvh]">
			<header className="px-4 lg:px-6 h-14 flex items-center">
				<Link
					href="/"
					className="flex items-center justify-center"
					prefetch={false}
				>
					<CompanyIcon />
					<span className="sr-only">Acme Inc</span>
				</Link>
				<nav className="ml-auto flex gap-4 sm:gap-6">
					<Link
						href="/"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Home
					</Link>
					<Link
						href="#"
						className="text-sm font-medium underline underline-offset-4"
						prefetch={false}
					>
						Features
					</Link>
					<Link
						href="/tutorial"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Tutorial
					</Link>
					{status === "authenticated" ? (
						<>
							<Link
								href="/community"
								className="text-sm font-medium hover:underline underline-offset-4"
								prefetch={false}
							>
								Community
							</Link>
							<Button onClick={handleSignOut}>Log Out</Button>
						</>
					) : (
						<Button onClick={handleSignIn}>Log In</Button>
					)}
				</nav>
			</header>
			<div className="flex flex-col min-h-[100dvh]">
				<section className="w-full py-12 md:py-24 lg:py-32 bg-primary">
					<div className="container px-4 md:px-6 text-center">
						<div className="max-w-3xl mx-auto space-y-4">
							<h1 className="text-3xl font-bold tracking-tighter text-primary-foreground sm:text-5xl md:text-6xl">
								간편한 비즈니스, 무한한 가능성
							</h1>
							<p className="text-primary-foreground text-lg md:text-xl">
								업무는 간편하게, 성과는 놀랍게! 서명기로 당신의 비즈니스를 한
								단계 더 도약시켜 보세요.
							</p>
						</div>
					</div>
				</section>
				<section className="w-full py-12 md:py-24 lg:py-32">
					<div className="container px-4 md:px-6">
						<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10">
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<GaugeIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">간편한 생성</h3>
								<p className="text-muted-foreground">
									몇 번의 클릭만으로 복잡한 문서를 쉽게 만들 수 있습니다. 시간은
									절약하고, 효율은 높이세요.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<GaugeIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">보이는 그대로</h3>
								<p className="text-muted-foreground">
									편집 화면에서 보는 그대로 결과물이 나옵니다. 더 이상의 예상치
									못한 변화는 없어요!
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<LayersIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">익숙한 UI</h3>
								<p className="text-muted-foreground">
									이미 익숙한 구굴의 사용자 인터페이스. 직관적인 디자인으로
									빠르게 적응하세요.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<AccessibilityIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">원 틀릭 서명</h3>
								<p className="text-muted-foreground">
									번거로운 서명 과정은 이제 그만! 한 번의 클릭으로 안전하고
									빠르게 서명하세요.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<ShieldIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">메일 전송</h3>
								<p className="text-muted-foreground">
									완성된 문서를 바로 이메일로 전송. 공유와 협업이 더욱
									쉬워집니다
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<RocketIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">보관</h3>
								<p className="text-muted-foreground">
									모든 문서를 안전하게 구굴 드라이브에 보관. 언제 어디서나
									필요한 자료에 접근하세요.
								</p>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	);
}

function AccessibilityIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<circle cx="16" cy="4" r="1" />
			<path d="m18 19 1-7-6 1" />
			<path d="m5 8 3-3 5.5 3-2.36 3.5" />
			<path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
			<path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
		</svg>
	);
}

function GaugeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m12 14 4-4" />
			<path d="M3.34 19a10 10 0 1 1 17.32 0" />
		</svg>
	);
}

function LayersIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
			<path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
			<path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
		</svg>
	);
}

function RocketIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
			<path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
			<path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
			<path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
		</svg>
	);
}

function ShieldIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
		</svg>
	);
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}

function CompanyIcon() {
	return <img src="/logo.png" alt="icon" className="h-14 w-24" />;
}

function MagicWandIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M22 11l-1-2-2 1-1-2-2 1-1-2-2 1 1 2-2 1-1 2 2-1 1 2 2-1 1 2 2-1 1 2 2-1-1-2 2-1zM15.6 14.6l-4.2 4.2-1.4-1.4 4.2-4.2-1.4-1.4 4.2-4.2 1.4 1.4-4.2 4.2 1.4 1.4zm-7.2 0l-4.2 4.2-1.4-1.4 4.2-4.2-1.4-1.4 4.2-4.2 1.4 1.4-4.2 4.2 1.4 1.4z" />
		</svg>
	);
}
