/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4XHRQLyNMjm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from "next/link";

export function FeaturesPage() {
	return (
		<div className="flex flex-col min-h-[100dvh]">
			<header className="px-4 lg:px-6 h-14 flex items-center">
				<Link
					href="#"
					className="flex items-center justify-center"
					prefetch={false}
				>
					<MountainIcon className="h-6 w-6" />
					<span className="sr-only">Acme Inc</span>
				</Link>
				<nav className="ml-auto flex gap-4 sm:gap-6">
					<Link
						href="/"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Home
					</Link>
					{/* <Link
						href="#"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Pricing
					</Link>
					<Link
						href="#"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						About
					</Link> */}
					<Link
						href="/community"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Community
					</Link>
				</nav>
			</header>
			<div className="flex flex-col min-h-[100dvh]">
				<section className="w-full py-12 md:py-24 lg:py-32 bg-primary">
					<div className="container px-4 md:px-6 text-center">
						<div className="max-w-3xl mx-auto space-y-4">
							<h1 className="text-3xl font-bold tracking-tighter text-primary-foreground sm:text-5xl md:text-6xl">
								Unlock Your Business Potential
							</h1>
							<p className="text-primary-foreground text-lg md:text-xl">
								Streamline your workflows, boost productivity, and take your
								business to new heights with our cutting-edge SaaS solution.
							</p>
						</div>
					</div>
				</section>
				<section className="w-full py-12 md:py-24 lg:py-32">
					<div className="container px-4 md:px-6">
						<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8 lg:gap-10">
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<GaugeIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">Blazing Fast Performance</h3>
								<p className="text-muted-foreground">
									Our SaaS is optimized for lightning-fast performance, ensuring
									your workflows are seamless and efficient.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<GaugeIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">Powerful Analytics</h3>
								<p className="text-muted-foreground">
									Gain deep insights into your business with our comprehensive
									analytics tools, helping you make data-driven decisions.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<LayersIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">Seamless Integrations</h3>
								<p className="text-muted-foreground">
									Seamlessly integrate our SaaS with your existing tools and
									workflows, creating a cohesive and efficient ecosystem.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<AccessibilityIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">
									Accessibility-First Design
								</h3>
								<p className="text-muted-foreground">
									Our SaaS is designed with accessibility in mind, ensuring
									everyone can use and benefit from our platform.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<ShieldIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">Enterprise-Grade Security</h3>
								<p className="text-muted-foreground">
									Rest assured that your data is secure with our
									industry-leading security measures and compliance standards.
								</p>
							</div>
							<div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-4">
								<div className="bg-muted rounded-md p-3 flex items-center justify-center">
									<RocketIcon className="w-8 h-8 text-muted-foreground" />
								</div>
								<h3 className="text-xl font-bold">Scalable and Flexible</h3>
								<p className="text-muted-foreground">
									Our SaaS is designed to scale with your business, offering the
									flexibility to adapt to your evolving needs.
								</p>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	);
}

function AccessibilityIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<circle cx="16" cy="4" r="1" />
			<path d="m18 19 1-7-6 1" />
			<path d="m5 8 3-3 5.5 3-2.36 3.5" />
			<path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
			<path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
		</svg>
	);
}

function GaugeIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m12 14 4-4" />
			<path d="M3.34 19a10 10 0 1 1 17.32 0" />
		</svg>
	);
}

function LayersIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
			<path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
			<path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
		</svg>
	);
}

function RocketIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
			<path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
			<path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
			<path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
		</svg>
	);
}

function ShieldIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
		</svg>
	);
}

function XIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}

function MountainIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m8 3 4 8 5-5 5 15H2L8 3z" />
		</svg>
	);
}
