/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/etEDzghkfuL
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
	Carousel,
	CarouselContent,
	CarouselItem,
	CarouselPrevious,
	CarouselNext,
} from "@/components/ui/carousel";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useSession } from "next-auth/react";

export function ResponsiveTemplateCarousel() {
	const { data: session, status } = useSession();
	return (
		<Carousel className="w-full max-w-4xl">
			<CarouselContent>
				<CarouselItem>
					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">근로계약서</h3>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/1u5qlCfmL5Wm2QBqNFXKjOLcLbmBDxHPKG4QZFTNcJMw/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">개인정보활용동의서</h3>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1u5qlCfmL5Wm2QBqNFXKjOLcLbmBDxHPKG4QZFTNcJMw/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/1usEbaOEjCaPT95ifFI1ZTIp0kvGpIc385HEU4BypzZE/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">상계계약서</h3>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1usEbaOEjCaPT95ifFI1ZTIp0kvGpIc385HEU4BypzZE/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
					</div>
				</CarouselItem>
				<CarouselItem>
					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/1nSgGZfL3DZrp4Xbzj6AvnqXep5E2IOG1gRDmqWMy9nw/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">채권채무상계계약서</h3>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1nSgGZfL3DZrp4Xbzj6AvnqXep5E2IOG1gRDmqWMy9nw/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/1ZEf8Ku1Bktj9oKugo-FeXhbw88-Sv166YsnvK2UiQ00/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">업무제휴 양해각서</h3>
							</div>
							<Button
								size="sm"
								onClick={() =>
									window.open(
										`https://docs.google.com/presentation/d/1ZEf8Ku1Bktj9oKugo-FeXhbw88-Sv166YsnvK2UiQ00/copy`,
										"_blank"
									)
								}
							>
								사용하기
							</Button>
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/166_bhAchy6Ms29oLPtAjtzla1iOxWLwd1iX8fnJ5Ato/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">중고자동차 매매계약서</h3>
							</div>
							<Button
								size="sm"
								onClick={() =>
									window.open(
										`https://docs.google.com/presentation/d/166_bhAchy6Ms29oLPtAjtzla1iOxWLwd1iX8fnJ5Ato/copy`,
										"_blank"
									)
								}
							>
								사용하기
							</Button>
						</Card>
					</div>
				</CarouselItem>
				{/* <CarouselItem>
					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">채권채무상계계약서</h3>
								<p className="text-muted-foreground">
									Protect your confidential information with this NDA template.
								</p>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1nSgGZfL3DZrp4Xbzj6AvnqXep5E2IOG1gRDmqWMy9nw/copy`,
											"_blank"
										)
									}
								>
									복사본 받기
								</Button>
							) : (
								<></>
							)}
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">
									Job Description Template
								</h3>
								<p className="text-muted-foreground">
									A customizable job description template for your company.
								</p>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1usEbaOEjCaPT95ifFI1ZTIp0kvGpIc385HEU4BypzZE/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
						<Card className="flex flex-col items-center gap-4 p-6">
							<img
								src="https://docs.google.com/presentation/d/18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8/export?format=png&pageid=p"
								width={300}
								height={200}
								alt="Template Thumbnail"
								className="rounded-md"
							/>
							<div className="text-center">
								<h3 className="text-lg font-semibold">Business Contract</h3>
								<p className="text-muted-foreground">
									A comprehensive contract template for business agreements.
								</p>
							</div>
							{status === "authenticated" ? (
								<Button
									size="sm"
									onClick={() =>
										window.open(
											`https://docs.google.com/presentation/d/1usEbaOEjCaPT95ifFI1ZTIp0kvGpIc385HEU4BypzZE/copy`,
											"_blank"
										)
									}
								>
									사용하기
								</Button>
							) : (
								<></>
							)}
						</Card>
					</div>
				</CarouselItem> */}
			</CarouselContent>
			<CarouselPrevious />
			<CarouselNext />
		</Carousel>
	);
}
