/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GTpjeKuEQbq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function TemplateCarousel() {
  return (
    <Carousel className="w-full max-w-4xl">
      <CarouselContent>
        <CarouselItem>
          <div className="grid grid-cols-3 gap-4">
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Business Contract</h3>
                <p className="text-muted-foreground">A comprehensive contract template for business agreements.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Invoice Template</h3>
                <p className="text-muted-foreground">A professional invoice template for your business.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Non-Disclosure Agreement</h3>
                <p className="text-muted-foreground">Protect your confidential information with this NDA template.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="grid grid-cols-3 gap-4">
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Job Description Template</h3>
                <p className="text-muted-foreground">A customizable job description template for your company.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Business Contract</h3>
                <p className="text-muted-foreground">A comprehensive contract template for business agreements.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Invoice Template</h3>
                <p className="text-muted-foreground">A professional invoice template for your business.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="grid grid-cols-3 gap-4">
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Non-Disclosure Agreement</h3>
                <p className="text-muted-foreground">Protect your confidential information with this NDA template.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Job Description Template</h3>
                <p className="text-muted-foreground">A customizable job description template for your company.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
            <Card className="flex flex-col items-center gap-4 p-6">
              <img src="/placeholder.svg" width={300} height={200} alt="Template Thumbnail" className="rounded-md" />
              <div className="text-center">
                <h3 className="text-lg font-semibold">Business Contract</h3>
                <p className="text-muted-foreground">A comprehensive contract template for business agreements.</p>
              </div>
              <Button size="sm">Get a Copy</Button>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
