/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6KIaPfGdYrN
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
	Collapsible,
	CollapsibleTrigger,
	CollapsibleContent,
} from "@/components/ui/collapsible";
import { JSX, SVGProps } from "react";
import React from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";

const SLIDE_ID = "18kr48JvRcEyeBo9IOlvadRfPIH27debHy1-xUM6M6x8";

export function TutorialPage() {
	const { data: session, status } = useSession();
	const router = useRouter();

	if (status === "loading") {
		return <div>Loading...</div>;
	}

	if (status === "unauthenticated") {
		router.push("/");
		return null;
	}

	const handleButtonClick = () => {
		window.open(
			`https://docs.google.com/presentation/d/${SLIDE_ID}/copy`,
			"_blank"
		);
	};
	return (
		<div className="flex flex-col min-h-[100dvh]">
			<header className="px-4 lg:px-6 h-14 flex items-center">
				<Link
					href="/"
					className="flex items-center justify-center"
					prefetch={false}
				>
					<CompanyIcon />
					<span className="sr-only">Acme Inc</span>
				</Link>
				<nav className="ml-auto flex gap-4 sm:gap-6">
					<Link
						href="/"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Home
					</Link>
					<Link
						href="/features"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Features
					</Link>
					{/* <Link
						href="#"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Pricing
					</Link>*/}
					<Link
						href="#"
						className="text-sm font-medium underline underline-offset-4"
						prefetch={false}
					>
						Tutorial
					</Link>
					<Link
						href="/community"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Community
					</Link>
				</nav>
			</header>
			<section className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
						<div className="flex flex-col justify-center space-y-4">
							<div className="space-y-2">
								<h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
									Get the Most Out of Our SaaS Platform
								</h1>
								<p className="max-w-[600px] text-muted-foreground md:text-xl">
									Follow these simple steps to unlock the full potential of our
									powerful SaaS tools and streamline your workflow.
								</p>
							</div>
							<button
								onClick={handleButtonClick}
								className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
							>
								Get Started
							</button>
							{/* <Link
								href="#"
								className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Get Started
							</Link> */}
						</div>
						<img
							src="/placeholder.svg"
							width="550"
							height="550"
							alt="Hero"
							className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
						/>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
				<div className="container px-4 md:px-6">
					<div className="space-y-8">
						<div className="space-y-2">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
								Step-by-Step Tutorial
							</h2>
							<p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								Follow these simple steps to get started with our SaaS platform
								and unlock its full potential.
							</p>
						</div>
						<div className="grid gap-6">
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											1
										</div>
										<h3 className="text-lg font-semibold">
											Create Your Account
										</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Start by signing up for a new account on our platform. This
										will give you access to all of our powerful tools and
										features.
									</p>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											2
										</div>
										<h3 className="text-lg font-semibold">
											Connect Your Data Sources
										</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Integrate your existing data sources, such as your
										e-commerce platform, CRM, or accounting software, to start
										leveraging our advanced analytics and reporting features.
									</p>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											3
										</div>
										<h3 className="text-lg font-semibold">
											Customize Your Dashboard
										</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Personalize your dashboard to display the metrics and
										insights that are most important to your business. Drag and
										drop widgets to create a custom layout that suits your
										needs.
									</p>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											4
										</div>
										<h3 className="text-lg font-semibold">
											Explore Advanced Features
										</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Dive into our powerful suite of tools, including predictive
										analytics, automated workflows, and collaborative features,
										to take your business to the next level.
									</p>
								</CollapsibleContent>
							</Collapsible>
						</div>
					</div>
				</div>
			</section>
		</div>
	);
}
function CompanyIcon() {
	return <img src="/icon.png" alt="icon" className="h-14 w-24" />;
}
