/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6KIaPfGdYrN
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
	Collapsible,
	CollapsibleTrigger,
	CollapsibleContent,
} from "@/components/ui/collapsible";

import React from "react";
import { Button } from "@/components/ui/button";

const SLIDE_ID = "1RQBSmZrNamMKE-9K3sTU_dFWLdJ-S34RKnKl6S_9ew4";

export function TutorialPage() {
	const handleButtonClick = async () => {
		window.open(
			`https://docs.google.com/presentation/d/${SLIDE_ID}/copy`,
			"_blank"
		);
	};

	const moveToTest = async () => {
		window.open(
			"https://script.google.com/macros/s/AKfycbxVP1Fz6mMHOSR2glUxWi9dQKnLooCbhU2k204lEer_V09zrRGJqHye526T0ba583OkOw/exec?target=minseochh02@gmail.com&id=10"
		);
	};

	return (
		<div className="flex flex-col min-h-[100dvh]">
			<header className="px-4 lg:px-6 h-14 flex items-center">
				<Link
					href="/"
					className="flex items-center justify-center"
					prefetch={false}
				>
					<CompanyIcon />
					<span className="sr-only">ExamAI</span>
				</Link>
				<nav className="ml-auto flex gap-4 sm:gap-6">
					<Link
						href="/"
						className="text-sm font-medium hover:underline underline-offset-4"
						prefetch={false}
					>
						Home
					</Link>
					<Link
						href="#"
						className="text-sm font-medium underline underline-offset-4"
						prefetch={false}
					>
						Tutorial
					</Link>
				</nav>
			</header>
			<section className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
						<div className="flex flex-col justify-center space-y-4">
							<div className="space-y-2">
								<h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
									ExamAI Tutorial:
								</h1>
								<p className="max-w-[600px] text-muted-foreground md:text-xl">
									Follow this guide to quickly set up, distribute, and grade
									your exams using ExamAI.
								</p>
							</div>
							<button
								onClick={handleButtonClick}
								className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
							>
								Unlock ExamAI in Your Drive
							</button>
						</div>
						<img
							src="/examAI-Full.png"
							width="550"
							height="550"
							alt="Hero"
							className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
						/>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
				<div className="container px-4 md:px-6">
					<div className="space-y-8">
						<div className="space-y-2">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
								ExamAI Tutorial
							</h2>
							<p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								It can&apost get easier
							</p>
						</div>
						<div className="grid gap-6">
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											1
										</div>
										<h3 className="text-lg font-semibold">Initiate</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>Wait for [Exam Tool] to appear at the top.</p>
									<p>
										allows ExamAI to access your Drive, Slides, and
										Spreadsheets. This enables ExamAI to create a personalized
										URL for your exam.
									</p>
									<img
										src="/examAI-permission.png"
										width="550"
										height="550"
										alt="Hero"
										className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
									/>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											2
										</div>
										<h3 className="text-lg font-semibold">Set Up</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>Creates a dedicated folder for your exam materials.</p>
									<p>
										Inside it gives you a new spreadsheet to track your exam
										questions and settings. Begin inputting your exam questions
										into the slide.
									</p>
									<img
										src="/examAI-setup.png"
										height="550"
										alt="Hero"
										className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
									/>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											3
										</div>
										<h3 className="text-lg font-semibold">Set Answers</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Automatically creates an answer sheet and OMR based on your
										current slide.
									</p>
									<img
										src="/examAI-setAnswers.png"
										width="550"
										height="550"
										alt="Hero"
										className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
									/>
								</CollapsibleContent>
							</Collapsible>
							<Collapsible className="rounded-lg border bg-background p-4 shadow-sm">
								<CollapsibleTrigger className="flex items-center justify-between">
									<div className="flex items-center gap-3">
										<div className="rounded-full bg-primary px-2 py-1 text-xs font-medium text-primary-foreground">
											4
										</div>
										<h3 className="text-lg font-semibold">Publish and Share</h3>
									</div>
									<div className="h-5 w-5 transition-transform data-[state=open]:rotate-90" />
								</CollapsibleTrigger>
								<CollapsibleContent className="mt-4 text-muted-foreground">
									<p>
										Select the exam pages you want to make available. Publish
										them to get a shareable URL.
									</p>
									<p>
										Distribute this URL to your students, and ExamAI will handle
										the rest, including grading!
									</p>
									<Button onClick={moveToTest}>Like This!</Button>
									<img
										src="/examAI-Final.png"
										width="550"
										height="550"
										alt="Hero"
										className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
									/>
								</CollapsibleContent>
							</Collapsible>
						</div>
					</div>
				</div>
			</section>
		</div>
	);
}
function CompanyIcon() {
	return <img src="/icon.png" alt="icon" className="h-14 w-24" />;
}
function Spinner() {
	return (
		<svg
			className="animate-spin h-5 w-5 text-white"
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
		>
			<circle
				className="opacity-25"
				cx="12"
				cy="12"
				r="10"
				stroke="currentColor"
				strokeWidth="4"
			></circle>
			<path
				className="opacity-75"
				fill="currentColor"
				d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
			></path>
		</svg>
	);
}
